onlyBuiltDependencies:
  - esbuild
catalog:
  "@sveltejs/adapter-static": ^3.0.10
  "@sveltejs/kit": ^2.49.1
  "@sveltejs/package": ^2.5.6
  "@sveltejs/vite-plugin-svelte": ^6.2.1
  "@tailwindcss/vite": ^4.1.17
  "svelte": ^5.45.6
  "svelte-check": ^4.3.4
  "publint": ^0.3.15
  "tailwindcss": ^4.1.17
  "typescript": ^5.9.3
  "vite": ^7.2.6
  "codemirror": ^6.0.2
  "dompurify": ^3.3.1
  "idb-keyval": ^6.2.2
  "uuid": ^13.0.0
  "postcss": ^8.5.6
  "@codemirror/lang-css": ^6.3.1
  "@codemirror/lang-markdown": ^6.5.0
  "@codemirror/theme-one-dark": ^6.1.3
  "@codemirror/state": ^6.5.4
  "@codemirror/view": ^6.39.11
  "@codemirror/commands": ^6.10.1
  "@codemirror/language-data": ^6.5.2
  "@fsegurai/codemirror-theme-vscode-dark": ^6.2.3
  "@fsegurai/codemirror-theme-vscode-light": ^6.2.3
  "@wenyan-md/core": ^2.0.1
catalogs:
  prod:
    svelte: ^5.0.0
    tailwindcss: ^4.0.0
